"""Run the complete external-source reconstruction offline, optionally comparing a release.

Run in a separate copy: source tables and evaluation outputs are regenerated in
that copy. No models are fitted; frozen primary predictions remain inputs.
"""
from __future__ import annotations

import argparse
from datetime import datetime, timezone
import hashlib
import json
import os
from pathlib import Path
import subprocess
import sys
import time

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
STAGES = [
    ('output/external_data_audit/extract_tables.py', []),
    ('output/external_data_audit/align_structures.py', ['--offline', '--rebuild-structures']),
    ('output/external_data_audit/audit_external_data.py', []),
    ('output/external_data_audit/verify_audit.py', []),
    ('output/external_evaluation/build_frozen_members.py', []),
    ('output/external_evaluation/frozen_evaluation.py', []),
]
GUARD = """import runpy, sys, urllib.request
from pathlib import Path
target = Path(sys.argv[1]).resolve()
sys.path.insert(0, str(target.parent))
sys.argv = [str(target), *sys.argv[2:]]
def forbidden(*args, **kwargs):
    raise RuntimeError('NETWORK_DISABLED_FOR_EXTERNAL_RECONSTRUCTION')
urllib.request.urlopen = forbidden
runpy.run_path(str(target), run_name='__main__')
"""


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def candidate_outputs():
    paths = []
    for folder in ('external_data_audit', 'frozen_external_feasibility', 'external_evaluation'):
        base = ROOT / 'output' / folder
        paths.extend(p for p in base.glob('*') if p.is_file() and p.suffix in ('.csv', '.json', '.npz'))
    return paths


def array_difference(a, b):
    assert a.shape == b.shape, f'array shape changed: {a.shape}, {b.shape}'
    if np.issubdtype(a.dtype, np.number) and np.issubdtype(b.dtype, np.number):
        assert np.array_equal(np.isnan(a), np.isnan(b)), 'missing-value pattern changed'
        assert np.allclose(a, b, atol=1e-12, rtol=0, equal_nan=True), 'numeric values changed beyond 1e-12'
        finite = np.isfinite(a) & np.isfinite(b)
        return float(np.max(np.abs(a[finite] - b[finite]))) if finite.any() else 0.
    assert np.array_equal(a, b), 'text/boolean array changed'
    return 0.


def normalize_json(name, value):
    value = json.loads(json.dumps(value))
    excluded = []
    if name == 'frozen_protocol.json':
        if 'primary_representation_prespecified' in value:
            value['primary_representation_designated'] = value.pop('primary_representation_prespecified')
        value['cohorts'].pop('quality_screen', None)
        excluded = ['designated versus unsupported prespecified key; score-free screen description replaces historical timing claim']
    elif name in ('verification.json', 'round1_verification.json'):
        for key in ('environment', 'checks_passed', 'checks', 'input_sha256', 'evaluation_script_sha256',
                    'numpy_version', 'pandas_version', 'python_version'):
            if key in value:
                value.pop(key)
                excluded.append(key)
    return value, excluded


def nested_difference(a, b):
    if isinstance(a, dict) and isinstance(b, dict):
        assert a.keys() == b.keys(), 'JSON field names differ'
        return max([nested_difference(a[k], b[k]) for k in a] or [0.])
    if isinstance(a, list) and isinstance(b, list):
        assert len(a) == len(b), 'JSON lengths differ'
        return max([nested_difference(x, y) for x, y in zip(a, b)] or [0.])
    if isinstance(a, (int, float)) and isinstance(b, (int, float)):
        return array_difference(np.array([a]), np.array([b]))
    assert a == b, f'JSON value changed: {a!r}, {b!r}'
    return 0.


def compare_outputs(paths, baseline):
    rows = []
    for path in sorted(paths):
        relative = path.relative_to(ROOT)
        prior = baseline / relative
        row = {'path': relative.as_posix(), 'status': 'passed', 'max_absolute_difference': 0.,
               'new_sha256': sha(path), 'baseline_sha256': sha(prior) if prior.exists() else '',
               'note': ''}
        if not prior.exists():
            if 'frozen_external_feasibility' in relative.parts:
                row.update(status='new_reconstructed_dependency', note='Newly restored generation dependency, not a recovered historical freeze')
            elif relative.as_posix() in ('output/external_data_audit/verification.json',
                                         'output/external_evaluation/verification.json',
                                         'output/external_evaluation/round1_verification.json'):
                row.update(status='new_verification_record', note='Generated by the documented reconstruction/verification commands; absent from the previous package')
            else:
                raise AssertionError(f'unexpected new output: {relative}')
            rows.append(row)
            continue
        try:
            if path.suffix == '.csv':
                a = pd.read_csv(prior, float_precision='round_trip')
                b = pd.read_csv(path, float_precision='round_trip')
                assert a.shape == b.shape and list(a.columns) == list(b.columns), 'CSV shape/columns changed'
                assert np.array_equal(a.isna(), b.isna()), 'CSV missing-value positions changed'
                difference = 0.
                for column in a:
                    if pd.api.types.is_numeric_dtype(a[column]) and pd.api.types.is_numeric_dtype(b[column]):
                        difference = max(difference, array_difference(a[column].to_numpy(), b[column].to_numpy()))
                    else:
                        assert a[column].fillna('<NA>').astype(str).equals(b[column].fillna('<NA>').astype(str)), f'CSV text changed: {column}'
                row['max_absolute_difference'] = difference
            elif path.suffix == '.npz':
                with np.load(prior, allow_pickle=False) as a, np.load(path, allow_pickle=False) as b:
                    assert a.files == b.files, 'bootstrap array keys changed'
                    row['max_absolute_difference'] = max(array_difference(a[key], b[key]) for key in a.files)
                    row['note'] = f'{len(a.files)} arrays compared, including all NaN/degenerate draws'
            else:
                a, exclusions = normalize_json(path.name, json.loads(prior.read_text(encoding='utf-8-sig')))
                b, _ = normalize_json(path.name, json.loads(path.read_text(encoding='utf-8-sig')))
                row['max_absolute_difference'] = nested_difference(a, b)
                row['note'] = '; '.join(exclusions)
        except (AssertionError, ValueError) as error:
            row.update(status='FAILED', note=str(error))
        rows.append(row)
    return rows


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--compare-to', type=Path, help='Original repository whose saved scientific outputs are compared')
    args = parser.parse_args()
    output = ROOT / 'results/reproducibility/external_rebuild'
    output.mkdir(parents=True, exist_ok=True)
    before = {str(path): path.stat().st_mtime_ns for path in candidate_outputs()}
    inputs = [*sorted((ROOT / 'data/external_raw').glob('*')),
              ROOT / 'output/external_data_audit/cache/pubchem_records.json',
              ROOT / 'results/primary/02_test_predictions.csv', ROOT / 'results/primary/01_representation_performance.csv']
    hashes = {path.relative_to(ROOT).as_posix(): sha(path) for path in inputs if path.is_file()}
    report = {'status': 'running', 'started_at_utc': datetime.now(timezone.utc).isoformat(),
              'root': str(ROOT), 'network_policy': 'urlopen is blocked in every subprocess; alignment also explicitly requires bundled responses',
              'input_sha256': hashes, 'models_fitted': 0, 'predictions_recomputed': 0, 'stages': []}
    destination = output / 'EXTERNAL_REBUILD_VERIFICATION.json'
    env = dict(os.environ, PYTHONUTF8='1', PYTHONIOENCODING='utf-8')
    for i, (relative, arguments) in enumerate(STAGES, 1):
        started = time.perf_counter()
        log = output / f'{i:02d}_{Path(relative).stem}.txt'
        with log.open('w', encoding='utf-8') as stream:
            process = subprocess.run([sys.executable, '-X', 'utf8', '-u', '-c', GUARD, relative, *arguments],
                                     cwd=ROOT, env=env, stdout=stream, stderr=subprocess.STDOUT)
        stage = {'script': relative, 'arguments': arguments, 'script_sha256': sha(ROOT / relative),
                 'exit_code': process.returncode, 'elapsed_seconds': time.perf_counter() - started,
                 'log': log.relative_to(ROOT).as_posix()}
        report['stages'].append(stage)
        destination.write_text(json.dumps(report, indent=2), encoding='utf-8')
        print(json.dumps(stage), flush=True)
        if process.returncode:
            report.update(status='FAILED', failure_stage=relative)
            destination.write_text(json.dumps(report, indent=2), encoding='utf-8')
            raise SystemExit(process.returncode)
    report['input_hashes_unchanged'] = all(sha(ROOT / name) == value for name, value in hashes.items())
    assert report['input_hashes_unchanged'], 'Frozen sources or primary predictions changed'
    generated = [path for path in candidate_outputs() if before.get(str(path)) != path.stat().st_mtime_ns]
    report['regenerated_outputs'] = [path.relative_to(ROOT).as_posix() for path in generated]
    report['comparison_policy'] = {'absolute_tolerance': 1e-12, 'relative_tolerance': 0,
                                   'CSV': 'identical shape, columns, row order, text and missingness',
                                   'NPZ': 'identical keys/shapes/missingness, every stored bootstrap draw compared'}
    report['status'] = 'passed'
    if args.compare_to:
        comparisons = compare_outputs(generated, args.compare_to.resolve())
        pd.DataFrame(comparisons).to_csv(output / 'external_rebuild_comparison.csv', index=False)
        report['baseline_repository'] = str(args.compare_to.resolve())
        report['compared_existing_outputs'] = sum(not row['status'].startswith('new_') for row in comparisons)
        report['new_reconstructed_dependencies'] = [row['path'] for row in comparisons if row['status'] == 'new_reconstructed_dependency']
        report['new_verification_records'] = [row['path'] for row in comparisons if row['status'] == 'new_verification_record']
        report['failures'] = [row for row in comparisons if row['status'] == 'FAILED']
        report['max_absolute_scientific_difference'] = max(row['max_absolute_difference'] for row in comparisons)
        if report['failures']:
            report['status'] = 'FAILED'
    report['finished_at_utc'] = datetime.now(timezone.utc).isoformat()
    destination.write_text(json.dumps(report, indent=2), encoding='utf-8')
    print(json.dumps({key: value for key, value in report.items() if key not in ('input_sha256', 'regenerated_outputs')}, indent=2))
    if report['status'] != 'passed':
        raise SystemExit(1)


if __name__ == '__main__':
    main()
